name: ngh-seis
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12.4
  - numpy=2.0.1
  - scipy=1.16.3
  - matplotlib=3.10.7
  - numba=0.62.1
  - pytorch=2.5.1
  - torchvision=0.20.1
  - pytorch-cuda=12.4
  - pip
  - pip:
      - deepwave==0.0.27
      - pytest>=8,<9
      - jupyterlab>=4,<5
